/* Generated By:JavaCC: Do not edit this line. Ejercicio1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Ejercicio1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MATRICULA = 1;
  /** RegularExpression Id. */
  int NOMBRE = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<MATRICULA>",
    "<NOMBRE>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
    "<token of kind 8>",
  };

}
